### ISSUE TITLE
Currently the multi-page setup nullifies the login page (users can go directly to the other pages without logging in)

### ISSUE THREAD

**Issue by durantschoon** [MoCoMakers/nf_streamlit#18]
Looks like there's a solution, we just need to prioritize this:

Discussion: https://discuss.streamlit.io/t/how-to-hide-all-pages-before-login/32508/26
Experimental repo with working `hide_pages()`: https://github.com/blackary/st_pages
Purported example of a working project with login + multiple pages: https://github.com/nelson123-lab/Hive

**Comment by mattzamora** [comment]
@ChubaOraka Please insert are login check & redirect if the user is not logged in when visiting the MIPE 3 0 page or the Delta S Prime page
